### ISSUE TITLE
How was the optimized_facenet.pb accquried from?

### ISSUE THREAD

**Issue by jianyin2016** [Qualeams/Android-Face-Recognition-with-Deep-Learning-Library#15]
I am trying to transplant the facenet model trained in GPU to android as the part  of the project does，unluckily，I got stuck as the original .pb file didn't work on the android for that the tensorflow things couldn't support some ops of the  serialized model,I try to solve it by using the optimized_for_inference tools embedded in tensorflow ,and the bazel can play a same role by my understanding.but I failed。。
T^T
this project has the optimized_facenet.pb which is exactly what I need and it works!even the whole project doesn't work on my PC with the reason unknown.
I wander How you guys  optimized the pb file so  that  it works on android things,please share it with me ,many many thanks!

**Comment by sladomic** [comment]
Hi,

I had the same problem with the Op Kernels. The problem was not the optimization but the freezing of the checkpoint model.

The mobile CPU/GPU doesn't support some operations yet and therefore the model crashes. There are basically 2 ways of fixing this

-  add the operation by yourself
-  get rid of the operation, if it is not mandatory for inference

I've found this pull request https://github.com/davidsandberg/facenet/pull/240/files from another user, who had the same issue and followed the 2nd option (to remove the unnecessary, but problematic Ops).

For me this worked:

1. Use the freeze_graph_resnet script to freeze the graph/model
2. Then use the optimization scripts to optimize the frozen model

Regards,
Michael

**Comment by jianyin2016** [comment]
@sladomic 
Hello, Michael~
your suggestion helps!

thanks for your attention and suggestion
